[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = ['rigged_mesh_manipulation']
cuda = ['multiple_masks_depthcorrected','multiple_masks','rigging','workflow']

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
